In [1]:
import pandas as pd

In [2]:
s= pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
s= pd.Series([1,2,3,4], index = ["A","B","C","D"])
s

A    1
B    2
C    3
D    4
dtype: int64

In [4]:
data =[[1,444,"abc"],
       [2,555,"ss"],
       [3,666,"ghi"]]

type(data)

list

In [7]:
df = pd.DataFrame(data)
df

   0    1    2
0  1  444  abc
1  2  555   ss
2  3  666  ghi

In [8]:
df = pd.DataFrame(data, columns= ['id','sal','dep'])
df

   id  sal  dep
0   1  444  abc
1   2  555   ss
2   3  666  ghi

In [9]:
cols = ['col1','col2','col3']
df = pd.DataFrame(data, columns = cols)
df

   col1  col2 col3
0     1   444  abc
1     2   555   ss
2     3   666  ghi

In [10]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [14]:
df.col2

0    444
1    555
2    666
Name: col2, dtype: int64

In [15]:
df[:]

   col1  col2 col3
0     1   444  abc
1     2   555   ss
2     3   666  ghi

In [16]:
df.dtypes

col1     int64
col2     int64
col3    object
dtype: object

In [17]:
df.col2.min()

444

In [20]:
df['col1']= df['col1'].astype('category')
df.dtypes

col1    category
col2       int64
col3      object
dtype: object

In [21]:
df.head()

  col1  col2 col3
0    1   444  abc
1    2   555   ss
2    3   666  ghi

In [22]:
df.head(-1)

  col1  col2 col3
0    1   444  abc
1    2   555   ss

In [23]:
df.tail()

  col1  col2 col3
0    1   444  abc
1    2   555   ss
2    3   666  ghi

In [24]:
df.tail(1)

  col1  col2 col3
2    3   666  ghi

In [27]:
df['col1']= df['col1'].astype('int')
df.dtypes

col1     int32
col2     int64
col3    object
dtype: object

In [28]:
df.describe()

       col1   col2
count   3.0    3.0
mean    2.0  555.0
std     1.0  111.0
min     1.0  444.0
25%     1.5  499.5
50%     2.0  555.0
75%     2.5  610.5
max     3.0  666.0

In [29]:
df['col1']= df['col1'].astype('category')

In [30]:
df.describe(include='category')

        col1
count      3
unique     3
top        1
freq       1

In [31]:
df.describe(include='all')

        col1   col2 col3
count    3.0    3.0    3
unique   3.0    NaN    3
top      1.0    NaN  abc
freq     1.0    NaN    1
mean     NaN  555.0  NaN
std      NaN  111.0  NaN
min      NaN  444.0  NaN
25%      NaN  499.5  NaN
50%      NaN  555.0  NaN
75%      NaN  610.5  NaN
max      NaN  666.0  NaN

In [32]:
df.col2.unique()

array([444, 555, 666], dtype=int64)

In [34]:
df['col2'].max()

666

In [37]:
def get_range(df):
    return df.max() - df.min()

get_range(df.col2)

222

In [38]:
df.col2.value_counts()

col2
444    1
555    1
666    1
Name: count, dtype: int64

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    3 non-null      category
 1   col2    3 non-null      int64
 2   col3    3 non-null      object
dtypes: category(1), int64(1), object(1)
memory usage: 283.0+ bytes